### ISSUE TITLE
NPE in neo4j kernel

### ISSUE THREAD

**Issue by pkocandr** [Commonjava/atlas#45]
With current AProx depgraph stack get an NPE when requesting urlmap in AProx.

21:24:32.270 [XNIO-1 task-2] ERROR io.undertow.request - UT005023: Exception handling request to /api/depgraph/repo/urlmap
org.jboss.resteasy.spi.UnhandledException: java.lang.NullPointerException
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:76) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:212) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:149) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:372) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[jboss-servlet-api_3.1_spec-1.0.0.Final.jar:1.0.0.Final]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:130) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
	at org.commonjava.aprox.bind.jaxrs.ResourceManagementFilter.doFilter(ResourceManagementFilter.java:60) ~[aprox-embedder-savant-0.25.0-SNAPSHOT.jar:na]
	at org.commonjava.aprox.bind.jaxrs.ResourceManagementFilter$Proxy$_$$_WeldClientProxy.doFilter(Unknown Source) ~[aprox-embedder-savant-0.25.0-SNAPSHOT.jar:na]
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45) ~[undertow-core-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:63) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58) ~[undertow-core-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76) ~[undertow-core-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-1.1.2.Final.jar:1.1.2.Final]
	at org.commonjava.aprox.bind.jaxrs.HeaderDebugger.handleRequest(HeaderDebugger.java:93) ~[aprox-embedder-savant-0.25.0-SNAPSHOT.jar:na]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:247) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:76) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:166) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197) ~[undertow-core-1.1.2.Final.jar:1.1.2.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:764) [undertow-core-1.1.2.Final.jar:1.1.2.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
Caused by: java.lang.NullPointerException: null
	at org.neo4j.kernel.impl.nioneo.xa.NioNeoDbPersistenceSource.createReadOnlyResourceConnection(NioNeoDbPersistenceSource.java:96) ~[neo4j-kernel-1.9.6.jar:1.9.6]
	at org.neo4j.kernel.impl.persistence.PersistenceManager.getReadOnlyResource(PersistenceManager.java:222) ~[neo4j-kernel-1.9.6.jar:1.9.6]
	at org.neo4j.kernel.impl.persistence.PersistenceManager.getReadOnlyResourceIfPossible(PersistenceManager.java:245) ~[neo4j-kernel-1.9.6.jar:1.9.6]
	at org.neo4j.kernel.impl.persistence.PersistenceManager.loadLightNode(PersistenceManager.java:73) ~[neo4j-kernel-1.9.6.jar:1.9.6]
	at org.neo4j.kernel.impl.core.NodeManager.getLightNode(NodeManager.java:453) ~[neo4j-kernel-1.9.6.jar:1.9.6]
	at org.neo4j.kernel.impl.core.NodeManager.getNodeForProxy(NodeManager.java:475) ~[neo4j-kernel-1.9.6.jar:1.9.6]
	at org.neo4j.kernel.InternalAbstractGraphDatabase$8.lookup(InternalAbstractGraphDatabase.java:785) ~[neo4j-kernel-1.9.6.jar:1.9.6]
	at org.neo4j.kernel.impl.core.NodeProxy.hasProperty(NodeProxy.java:160) ~[neo4j-kernel-1.9.6.jar:1.9.6]
	at org.commonjava.maven.atlas.graph.spi.neo4j.io.Conversions.getStringProperty(Conversions.java:559) ~[atlas-driver-neo4j-embedded-0.16.0-SNAPSHOT.jar:na]
	at org.commonjava.maven.atlas.graph.spi.neo4j.model.NeoIdentityUtils.getStringProperty(NeoIdentityUtils.java:58) ~[atlas-driver-neo4j-embedded-0.16.0-SNAPSHOT.jar:na]
	at org.commonjava.maven.atlas.graph.spi.neo4j.model.NeoProjectRef.getArtifactId(NeoProjectRef.java:125) ~[atlas-driver-neo4j-embedded-0.16.0-SNAPSHOT.jar:na]
	at org.commonjava.maven.atlas.graph.spi.neo4j.model.NeoProjectRef.hashCode(NeoProjectRef.java:182) ~[atlas-driver-neo4j-embedded-0.16.0-SNAPSHOT.jar:na]
	at org.commonjava.maven.atlas.graph.spi.neo4j.model.NeoProjectVersionRef.hashCode(NeoProjectVersionRef.java:251) ~[atlas-driver-neo4j-embedded-0.16.0-SNAPSHOT.jar:na]
	at java.util.HashMap.hash(HashMap.java:338) ~[na:1.8.0_60]
	at java.util.HashMap.get(HashMap.java:556) ~[na:1.8.0_60]
	at org.commonjava.cartographer.INTERNAL.ops.ResolveOpsImpl.resolveRepositoryContents(ResolveOpsImpl.java:131) ~[aprox-embedder-savant-0.25.0-SNAPSHOT.jar:na]
	at org.commonjava.aprox.depgraph.rest.RepositoryController.resolveContents(RepositoryController.java:256) ~[aprox-embedder-savant-0.25.0-SNAPSHOT.jar:na]
	at org.commonjava.aprox.depgraph.rest.RepositoryController.getUrlMap(RepositoryController.java:96) ~[aprox-embedder-savant-0.25.0-SNAPSHOT.jar:na]
	at org.commonjava.aprox.depgraph.rest.RepositoryController$Proxy$_$$_WeldClientProxy.getUrlMap(Unknown Source) ~[aprox-embedder-savant-0.25.0-SNAPSHOT.jar:na]
	at org.commonjava.aprox.depgraph.jaxrs.render.RepositoryResource.getUrlMap(RepositoryResource.java:86) ~[aprox-embedder-savant-0.25.0-SNAPSHOT.jar:na]
	at org.commonjava.aprox.depgraph.jaxrs.render.RepositoryResource$Proxy$_$$_WeldClientProxy.getUrlMap(Unknown Source) ~[aprox-embedder-savant-0.25.0-SNAPSHOT.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
	... 34 common frames omitted

**Comment by pkocandr** [comment]
I'm not sure if the problem is in NEO4J or in its bad usage.

**Comment by jdcasey** [comment]
Hm, I think this might be because the objects being serialized are neo4j wrappers, and the cartographer operations close the graph connection after extracting the information. I think just converting them to Simple** forms before closing the connection would probably work.

**Comment by jdcasey** [comment]
Implemented detach feature for neo4j implementations of identities+relationships, and call detach before returning results from most public method calls to FileNeo4jGraphConnection
