### ISSUE TITLE
IllegalArgumentException when fetching objects from database

### ISSUE THREAD

**Issue by pkocandr** [Commonjava/atlas#60]
```
04:59:27.252 [POST /depgraph/graph/paths] INFO  o.c.m.a.g.RelationshipGraphFactory$ConnectionCache - Starting close-cache countdown for: brms-bpmsuite-6.1.5.GA-redhat-1-example (5000ms)
04:59:27.254 [XNIO-1 task-21] ERROR io.undertow.request - UT005023: Exception handling request to /api/depgraph/graph/paths
org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:76) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:212) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:149) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:372) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
        at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[jboss-servlet-api_3.1_spec-1.0.0.Final.jar:1.0.0.Final]
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:130) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
        at org.commonjava.indy.bind.jaxrs.ResourceManagementFilter.doFilter(ResourceManagementFilter.java:60) ~[indy-embedder-savant-1.0-SNAPSHOT.jar:na]
        at org.commonjava.indy.bind.jaxrs.ResourceManagementFilter$Proxy$_$$_WeldClientProxy.doFilter(Unknown Source) ~[indy-embedder-savant-1.0-SNAPSHOT.jar:na]
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:61) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:56) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:45) ~[undertow-core-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:63) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58) ~[undertow-core-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76) ~[undertow-core-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-1.1.2.Final.jar:1.1.2.Final]
        at org.commonjava.indy.bind.jaxrs.HeaderDebugger.handleRequest(HeaderDebugger.java:93) ~[indy-embedder-savant-1.0-SNAPSHOT.jar:na]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) ~[undertow-core-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:247) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:76) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:166) ~[undertow-servlet-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:197) ~[undertow-core-1.1.2.Final.jar:1.1.2.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:764) [undertow-core-1.1.2.Final.jar:1.1.2.Final]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_51]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_51]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeLo(TimSort.java:773) ~[na:1.8.0_51]
        at java.util.TimSort.mergeAt(TimSort.java:510) ~[na:1.8.0_51]
        at java.util.TimSort.mergeCollapse(TimSort.java:437) ~[na:1.8.0_51]
        at java.util.TimSort.sort(TimSort.java:241) ~[na:1.8.0_51]
        at java.util.Arrays.sort(Arrays.java:1512) ~[na:1.8.0_51]
        at java.util.ArrayList.sort(ArrayList.java:1454) ~[na:1.8.0_51]
        at java.util.Collections.sort(Collections.java:175) ~[na:1.8.0_51]
        at org.neo4j.kernel.impl.traversal.SortingTraverserIterator.fetchAndSortResult(SortingTraverserIterator.java:109) ~[neo4j-kernel-1.9.6.jar:1.9.6]
        at org.neo4j.kernel.impl.traversal.SortingTraverserIterator.fetchNextOrNull(SortingTraverserIterator.java:97) ~[neo4j-kernel-1.9.6.jar:1.9.6]
        at org.neo4j.kernel.impl.traversal.SortingTraverserIterator.fetchNextOrNull(SortingTraverserIterator.java:34) ~[neo4j-kernel-1.9.6.jar:1.9.6]
        at org.neo4j.helpers.collection.PrefetchingIterator.hasNext(PrefetchingIterator.java:55) ~[neo4j-kernel-1.9.6.jar:1.9.6]
        at org.commonjava.maven.atlas.graph.spi.neo4j.FileNeo4JGraphConnection.traverse(FileNeo4JGraphConnection.java:890) ~[atlas-driver-neo4j-embedded-0.15.3-SNAPSHOT.jar:na]
        at org.commonjava.maven.atlas.graph.RelationshipGraph.traverse(RelationshipGraph.java:323) ~[atlas-relationships-api-0.15.3-SNAPSHOT.jar:na]
        at org.commonjava.cartographer.INTERNAL.ops.GraphOpsImpl.lambda$getPaths$6(GraphOpsImpl.java:103) ~[indy-embedder-savant-1.0-SNAPSHOT.jar:na]
        at org.commonjava.cartographer.INTERNAL.ops.GraphOpsImpl$$Lambda$16/1085985479.extract(Unknown Source) ~[na:na]
        at org.commonjava.cartographer.graph.GraphResolver.resolveAndExtractMultiGraph(GraphResolver.java:184) ~[indy-embedder-savant-1.0-SNAPSHOT.jar:na]
        at org.commonjava.cartographer.INTERNAL.ops.GraphOpsImpl.getPaths(GraphOpsImpl.java:137) ~[indy-embedder-savant-1.0-SNAPSHOT.jar:na]
        at org.commonjava.indy.depgraph.rest.GraphController.getPaths(GraphController.java:85) ~[indy-embedder-savant-1.0-SNAPSHOT.jar:na]
        at org.commonjava.indy.depgraph.jaxrs.GraphResource.getPaths(GraphResource.java:56) ~[indy-embedder-savant-1.0-SNAPSHOT.jar:na]
        at org.commonjava.indy.depgraph.jaxrs.GraphResource$Proxy$_$$_WeldClientProxy.getPaths(Unknown Source) ~[indy-embedder-savant-1.0-SNAPSHOT.jar:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_51]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_51]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_51]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_51]
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:296) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:250) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:237) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356) ~[resteasy-jaxrs-3.0.9.Final.jar:na]
        ... 34 common frames omitted
```

It seems some compareTo() method of a NeoXXX class is not implemented properly.

**Comment by pkocandr** [comment]
Bad guess, the problem seems to be in PathComparator.

**Comment by pkocandr** [comment]
It seems I fixed that, I'm running more tests. I think I'll be able to send a PR tomorrow.
